on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: macos-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'pnpm'
      
    - name: 🔨 Build Project
      run: |
        pnpm install
        pnpm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: mediakular.com
        username: veggie_user
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./build/
