on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: macos-latest
    steps:
    - name: Set up environment variables
      run: echo "PUBLIC_POCKETBASE_URL=${{ vars.PUBLIC_POCKETBASE_URL }}" >> $GITHUB_ENV
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: mediakular.com
        username: veggie_user
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 21
        local-dir: ./build/
